### ISSUE TITLE
Origin/Destination UI Component for Trip Planning

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/otpkit#13]
**As a** frequent public transit user,
**I want** to easily input my trip's origin and destination within the OneBusAway app,
**so that** I can quickly and accurately plan my route using public transportation.

#### Functional Requirements

1. **Input Fields**:
   - The UI should have two clearly labeled input fields for the origin and destination.
   - Each input field should support text input and autocomplete suggestions based on nearby locations and recent searches.

1. **Autocomplete Suggestions**:
   - Display a list of autocomplete suggestions as the user types, including recent search history and popular locations.
   - Suggestions should be fetched in real-time and displayed dynamically.

1. **Error Handling**:
   - Validate the input fields to ensure valid addresses or transit stops are entered.
   - Display appropriate error messages if the input cannot be recognized.

1. **Accessibility**:
   - Ensure the component is fully accessible, with support for VoiceOver and dynamic text resizing.
   - Provide clear labels and instructions for screen reader users.

#### Non-Functional Requirements

**Usability**:
   - The UI should be intuitive and easy to use, with minimal steps required to input origin and destination.
   - Provide visual feedback when locations are selected or errors occur.

**Scalability**:
   - Design the component to handle a large number of suggestions and high traffic without performance degradation.

**Compatibility**:
   - The component should work seamlessly across various iOS devices and screen sizes.
   - Ensure compatibility with iOS 16 and 17.

**Comment by hilmyveradin** [comment]
This issue is chucked to 4 different issues:

#14 
#15 
#29 
#30
