### ISSUE TITLE
Origin/Destination - Core UI

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/otpkit#16]
This is the key UI component of the trip planner experience. Here, a user will choose their origin and destination—or more likely have their origin pre-filled and select their destination. The origin/destination should be built as a List in SwiftUI to account for future feature improvements like stopovers, rearranging, etc.

Tapping on the origin or destination items will bring up a modal search controller, similar to what is seen in the Apple Maps app. Searching for a destination will use [MKLocalSearchCompleter](https://developer.apple.com/documentation/mapkit/mklocalsearchcompleter) or something similar. (e.g. if there happens to be a newer class somewhere in MapKit.)

**Mockup**

See the portion in red.

![Image](https://github.com/OneBusAway/otpkit/assets/2254/db870e02-9a24-4907-8536-1d3538047712)

![Image](https://github.com/OneBusAway/otpkit/assets/2254/e166441e-cef1-459b-9a71-75d8ef5f3f18)

**Comment by hilmyveradin** [comment]
https://github.com/OneBusAway/otpkit/pull/19
