### ISSUE TITLE
Favorites and Recents "More" modals disappear on first tap

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/otpkit#26]
Repro:

1. Launch the app
2. Tap on the "Origin UI" button
3. Tap on "More" next to Favorites or Recents

Expected:

The modal view controller appears and does not immediately disappear.

Actual:

The modal view controller appears and immediately disappears. See GIF below.

![2024-07-13 22 21 04](https://github.com/user-attachments/assets/60fc7edb-ad09-4524-b405-c4ae0acd0f28)

**Comment by hilmyveradin** [comment]
Hi @aaronbrethorst, just wondering, can you try to remove the app, fresh install the app? I tried to repro this by fresh installing the app and it works just fine. Take a look at the video below:

https://github.com/user-attachments/assets/88029f14-cd05-4882-9b07-f3ebd6b5adff

Seems like it doesn't happen in my case. So I'm not really sure...

**Comment by aaronbrethorst** [comment]
I'm still seeing it, unfortunately, even after deleting the app and reinstalling fresh. Here's what I see in the Xcode console:

```
Attempt to present <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x107035000> on <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x10700ca00> (from <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x10700ca00>) while a presentation is in progress.
```

Let's not worry about this for the time being, though. There are bigger, more important issues to tackle :)
