### ISSUE TITLE
Migrate to iOS 17 macro-based observation

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/otpkit#52]
https://wwdcnotes.com/documentation/wwdcnotes/wwdc23-10148-whats-new-in-swiftui

**Comment by hilmyveradin** [comment]
Is this the main reference for the observable macro?

https://developer.apple.com/documentation/swiftui/migrating-from-the-observable-object-protocol-to-the-observable-macro/

**Comment by aaronbrethorst** [comment]
Yep that’s the one!
